import type { LevelDefinition, TileKind } from './types'

const allKinds: TileKind[] = [
  'ruby',
  'amber',
  'emerald',
  'sapphire',
  'violet',
  'rose',
  'teal',
]

const handcraftedLevels: LevelDefinition[] = [
  {
    id: 1,
    name: '启程训练',
    summary: '6x6 棋盘，先熟悉基础三连与掉落。',
    rows: 6,
    columns: 6,
    tileKinds: allKinds.slice(0, 4),
    targetScore: 260,
    timeLimit: 80,
    timeBonus: 8,
    pointsPerTile: 18,
    chainBonus: 40,
    handcrafted: true,
  },
  {
    id: 2,
    name: '双线推进',
    summary: '继续使用 4 种宝石，目标分数略微提高。',
    rows: 6,
    columns: 6,
    tileKinds: allKinds.slice(0, 4),
    targetScore: 330,
    timeLimit: 78,
    timeBonus: 8,
    pointsPerTile: 18,
    chainBonus: 44,
    handcrafted: true,
  },
  {
    id: 3,
    name: '节奏切换',
    summary: '更短的时间窗口，鼓励更快完成连消。',
    rows: 6,
    columns: 6,
    tileKinds: allKinds.slice(0, 4),
    targetScore: 390,
    timeLimit: 74,
    timeBonus: 9,
    pointsPerTile: 19,
    chainBonus: 48,
    handcrafted: true,
  },
  {
    id: 4,
    name: '多彩上场',
    summary: '加入第 5 种宝石，局面开始变复杂。',
    rows: 6,
    columns: 6,
    tileKinds: allKinds.slice(0, 5),
    targetScore: 450,
    timeLimit: 76,
    timeBonus: 9,
    pointsPerTile: 19,
    chainBonus: 54,
    handcrafted: true,
  },
  {
    id: 5,
    name: '紧凑布局',
    summary: '目标继续提升，适合练习观察纵向连线。',
    rows: 6,
    columns: 6,
    tileKinds: allKinds.slice(0, 5),
    targetScore: 520,
    timeLimit: 74,
    timeBonus: 10,
    pointsPerTile: 20,
    chainBonus: 58,
    handcrafted: true,
  },
  {
    id: 6,
    name: '七列展开',
    summary: '棋盘扩展到 7x7，需要更快扫描全局。',
    rows: 7,
    columns: 7,
    tileKinds: allKinds.slice(0, 5),
    targetScore: 620,
    timeLimit: 88,
    timeBonus: 10,
    pointsPerTile: 20,
    chainBonus: 62,
    handcrafted: true,
  },
  {
    id: 7,
    name: '层层连锁',
    summary: '鼓励制造二段以上连锁，时间奖励更高。',
    rows: 7,
    columns: 7,
    tileKinds: allKinds.slice(0, 5),
    targetScore: 710,
    timeLimit: 86,
    timeBonus: 11,
    pointsPerTile: 21,
    chainBonus: 68,
    handcrafted: true,
  },
  {
    id: 8,
    name: '色彩压缩',
    summary: '第 6 种宝石加入后，可用交换会更稀疏。',
    rows: 7,
    columns: 7,
    tileKinds: allKinds.slice(0, 6),
    targetScore: 820,
    timeLimit: 84,
    timeBonus: 11,
    pointsPerTile: 22,
    chainBonus: 74,
    handcrafted: true,
  },
  {
    id: 9,
    name: '稳中求快',
    summary: '在更高目标下保持操作效率。',
    rows: 7,
    columns: 7,
    tileKinds: allKinds.slice(0, 6),
    targetScore: 920,
    timeLimit: 82,
    timeBonus: 12,
    pointsPerTile: 22,
    chainBonus: 78,
    handcrafted: true,
  },
  {
    id: 10,
    name: '全面观察',
    summary: '切换到 8x8 棋盘，兼顾横纵两条思路。',
    rows: 8,
    columns: 8,
    tileKinds: allKinds.slice(0, 6),
    targetScore: 1030,
    timeLimit: 94,
    timeBonus: 12,
    pointsPerTile: 22,
    chainBonus: 84,
    handcrafted: true,
  },
  {
    id: 11,
    name: '连续冲刺',
    summary: '更高分数线，适合利用掉落形成补消。',
    rows: 8,
    columns: 8,
    tileKinds: allKinds.slice(0, 6),
    targetScore: 1140,
    timeLimit: 92,
    timeBonus: 13,
    pointsPerTile: 23,
    chainBonus: 88,
    handcrafted: true,
  },
  {
    id: 12,
    name: '高手预热',
    summary: '前段手工关收尾，难度趋近后续生成关。',
    rows: 8,
    columns: 8,
    tileKinds: allKinds,
    targetScore: 1260,
    timeLimit: 90,
    timeBonus: 13,
    pointsPerTile: 23,
    chainBonus: 94,
    handcrafted: true,
  },
  {
    id: 13,
    name: '转换齿轮',
    summary: '开始进入混合模式，时间更紧但分数收益更高。',
    rows: 8,
    columns: 8,
    tileKinds: allKinds,
    targetScore: 1390,
    timeLimit: 88,
    timeBonus: 14,
    pointsPerTile: 24,
    chainBonus: 98,
    handcrafted: true,
  },
  {
    id: 14,
    name: '加速堆叠',
    summary: '快速判断潜在连锁路线，压缩通关时间。',
    rows: 8,
    columns: 8,
    tileKinds: allKinds,
    targetScore: 1520,
    timeLimit: 86,
    timeBonus: 14,
    pointsPerTile: 24,
    chainBonus: 102,
    handcrafted: true,
  },
  {
    id: 15,
    name: '百关正赛',
    summary: '手工配置阶段的最终热身关。',
    rows: 8,
    columns: 8,
    tileKinds: allKinds,
    targetScore: 1660,
    timeLimit: 84,
    timeBonus: 15,
    pointsPerTile: 25,
    chainBonus: 108,
    handcrafted: true,
  },
]

const generatedTags = ['疾速', '稳压', '聚能', '裂变', '穿梭', '跃迁', '凌峰', '回响']

function generateLevel(id: number): LevelDefinition {
  const generatedIndex = id - handcraftedLevels.length - 1
  const rows = id <= 32 ? 7 : 8
  const columns = id <= 20 ? 7 : 8
  const kindCount = Math.min(7, 5 + Math.floor(generatedIndex / 22))
  const intensity = generatedIndex + 1
  const tag = generatedTags[generatedIndex % generatedTags.length]

  return {
    id,
    name: `${tag} ${id}`,
    summary: `程序生成关卡，难度会随关卡编号逐步上升。`,
    rows,
    columns,
    tileKinds: allKinds.slice(0, kindCount),
    targetScore: 1780 + intensity * 42 + rows * columns * 3,
    timeLimit: Math.max(52, 84 - Math.floor(intensity / 3)),
    timeBonus: 15 + Math.floor(intensity / 6),
    pointsPerTile: 25 + Math.floor(intensity / 10),
    chainBonus: 112 + intensity * 3,
    handcrafted: false,
  }
}

export const levels: LevelDefinition[] = [
  ...handcraftedLevels,
  ...Array.from({ length: 100 - handcraftedLevels.length }, (_, index) =>
    generateLevel(handcraftedLevels.length + index + 1),
  ),
]

export function getLevel(levelId: number): LevelDefinition {
  return levels[Math.min(Math.max(levelId, 1), levels.length) - 1]
}
